/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppSnippetsIndexRouteImport } from './routes/_app/snippets/index'
import { Route as AppCollectionsIndexRouteImport } from './routes/_app/collections/index'
import { Route as AppSnippetsNewRouteImport } from './routes/_app/snippets/new'
import { Route as AppSnippetsIdRouteImport } from './routes/_app/snippets/$id'
import { Route as AppCollectionsIdRouteImport } from './routes/_app/collections/$id'
import { Route as AppSnippetsIdEditRouteImport } from './routes/_app/snippets/$id.edit'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSnippetsIndexRoute = AppSnippetsIndexRouteImport.update({
  id: '/snippets/',
  path: '/snippets/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCollectionsIndexRoute = AppCollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSnippetsNewRoute = AppSnippetsNewRouteImport.update({
  id: '/snippets/new',
  path: '/snippets/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSnippetsIdRoute = AppSnippetsIdRouteImport.update({
  id: '/snippets/$id',
  path: '/snippets/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCollectionsIdRoute = AppCollectionsIdRouteImport.update({
  id: '/collections/$id',
  path: '/collections/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSnippetsIdEditRoute = AppSnippetsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppSnippetsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/collections/$id': typeof AppCollectionsIdRoute
  '/snippets/$id': typeof AppSnippetsIdRouteWithChildren
  '/snippets/new': typeof AppSnippetsNewRoute
  '/collections/': typeof AppCollectionsIndexRoute
  '/snippets/': typeof AppSnippetsIndexRoute
  '/snippets/$id/edit': typeof AppSnippetsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/collections/$id': typeof AppCollectionsIdRoute
  '/snippets/$id': typeof AppSnippetsIdRouteWithChildren
  '/snippets/new': typeof AppSnippetsNewRoute
  '/collections': typeof AppCollectionsIndexRoute
  '/snippets': typeof AppSnippetsIndexRoute
  '/snippets/$id/edit': typeof AppSnippetsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_app/collections/$id': typeof AppCollectionsIdRoute
  '/_app/snippets/$id': typeof AppSnippetsIdRouteWithChildren
  '/_app/snippets/new': typeof AppSnippetsNewRoute
  '/_app/collections/': typeof AppCollectionsIndexRoute
  '/_app/snippets/': typeof AppSnippetsIndexRoute
  '/_app/snippets/$id/edit': typeof AppSnippetsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/collections/$id'
    | '/snippets/$id'
    | '/snippets/new'
    | '/collections/'
    | '/snippets/'
    | '/snippets/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/collections/$id'
    | '/snippets/$id'
    | '/snippets/new'
    | '/collections'
    | '/snippets'
    | '/snippets/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/dashboard'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_app/collections/$id'
    | '/_app/snippets/$id'
    | '/_app/snippets/new'
    | '/_app/collections/'
    | '/_app/snippets/'
    | '/_app/snippets/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/snippets/': {
      id: '/_app/snippets/'
      path: '/snippets'
      fullPath: '/snippets/'
      preLoaderRoute: typeof AppSnippetsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/collections/': {
      id: '/_app/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof AppCollectionsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/snippets/new': {
      id: '/_app/snippets/new'
      path: '/snippets/new'
      fullPath: '/snippets/new'
      preLoaderRoute: typeof AppSnippetsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/snippets/$id': {
      id: '/_app/snippets/$id'
      path: '/snippets/$id'
      fullPath: '/snippets/$id'
      preLoaderRoute: typeof AppSnippetsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/collections/$id': {
      id: '/_app/collections/$id'
      path: '/collections/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof AppCollectionsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/snippets/$id/edit': {
      id: '/_app/snippets/$id/edit'
      path: '/edit'
      fullPath: '/snippets/$id/edit'
      preLoaderRoute: typeof AppSnippetsIdEditRouteImport
      parentRoute: typeof AppSnippetsIdRoute
    }
  }
}

interface AppSnippetsIdRouteChildren {
  AppSnippetsIdEditRoute: typeof AppSnippetsIdEditRoute
}

const AppSnippetsIdRouteChildren: AppSnippetsIdRouteChildren = {
  AppSnippetsIdEditRoute: AppSnippetsIdEditRoute,
}

const AppSnippetsIdRouteWithChildren = AppSnippetsIdRoute._addFileChildren(
  AppSnippetsIdRouteChildren,
)

interface AppRouteRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppCollectionsIdRoute: typeof AppCollectionsIdRoute
  AppSnippetsIdRoute: typeof AppSnippetsIdRouteWithChildren
  AppSnippetsNewRoute: typeof AppSnippetsNewRoute
  AppCollectionsIndexRoute: typeof AppCollectionsIndexRoute
  AppSnippetsIndexRoute: typeof AppSnippetsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppCollectionsIdRoute: AppCollectionsIdRoute,
  AppSnippetsIdRoute: AppSnippetsIdRouteWithChildren,
  AppSnippetsNewRoute: AppSnippetsNewRoute,
  AppCollectionsIndexRoute: AppCollectionsIndexRoute,
  AppSnippetsIndexRoute: AppSnippetsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
