/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppSnippetsRouteImport } from './routes/_app/snippets'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCollectionRouteImport } from './routes/_app/collection'
import { Route as AppSnippetsNewRouteImport } from './routes/_app/snippets/new'
import { Route as AppSnippetsIdRouteImport } from './routes/_app/snippets/$id'
import { Route as AppCollectionsIdRouteImport } from './routes/_app/collections/$id'
import { Route as AppSnippetsIdEditRouteImport } from './routes/_app/snippets/$id.edit'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppSnippetsRoute = AppSnippetsRouteImport.update({
  id: '/snippets',
  path: '/snippets',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCollectionRoute = AppCollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSnippetsNewRoute = AppSnippetsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppSnippetsRoute,
} as any)
const AppSnippetsIdRoute = AppSnippetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppSnippetsRoute,
} as any)
const AppCollectionsIdRoute = AppCollectionsIdRouteImport.update({
  id: '/collections/$id',
  path: '/collections/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSnippetsIdEditRoute = AppSnippetsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppSnippetsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collection': typeof AppCollectionRoute
  '/dashboard': typeof AppDashboardRoute
  '/snippets': typeof AppSnippetsRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/collections/$id': typeof AppCollectionsIdRoute
  '/snippets/$id': typeof AppSnippetsIdRouteWithChildren
  '/snippets/new': typeof AppSnippetsNewRoute
  '/snippets/$id/edit': typeof AppSnippetsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collection': typeof AppCollectionRoute
  '/dashboard': typeof AppDashboardRoute
  '/snippets': typeof AppSnippetsRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/collections/$id': typeof AppCollectionsIdRoute
  '/snippets/$id': typeof AppSnippetsIdRouteWithChildren
  '/snippets/new': typeof AppSnippetsNewRoute
  '/snippets/$id/edit': typeof AppSnippetsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_app/collection': typeof AppCollectionRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/snippets': typeof AppSnippetsRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_app/collections/$id': typeof AppCollectionsIdRoute
  '/_app/snippets/$id': typeof AppSnippetsIdRouteWithChildren
  '/_app/snippets/new': typeof AppSnippetsNewRoute
  '/_app/snippets/$id/edit': typeof AppSnippetsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collection'
    | '/dashboard'
    | '/snippets'
    | '/login'
    | '/register'
    | '/collections/$id'
    | '/snippets/$id'
    | '/snippets/new'
    | '/snippets/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collection'
    | '/dashboard'
    | '/snippets'
    | '/login'
    | '/register'
    | '/collections/$id'
    | '/snippets/$id'
    | '/snippets/new'
    | '/snippets/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/collection'
    | '/_app/dashboard'
    | '/_app/snippets'
    | '/_auth/login'
    | '/_auth/register'
    | '/_app/collections/$id'
    | '/_app/snippets/$id'
    | '/_app/snippets/new'
    | '/_app/snippets/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/snippets': {
      id: '/_app/snippets'
      path: '/snippets'
      fullPath: '/snippets'
      preLoaderRoute: typeof AppSnippetsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/collection': {
      id: '/_app/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof AppCollectionRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/snippets/new': {
      id: '/_app/snippets/new'
      path: '/new'
      fullPath: '/snippets/new'
      preLoaderRoute: typeof AppSnippetsNewRouteImport
      parentRoute: typeof AppSnippetsRoute
    }
    '/_app/snippets/$id': {
      id: '/_app/snippets/$id'
      path: '/$id'
      fullPath: '/snippets/$id'
      preLoaderRoute: typeof AppSnippetsIdRouteImport
      parentRoute: typeof AppSnippetsRoute
    }
    '/_app/collections/$id': {
      id: '/_app/collections/$id'
      path: '/collections/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof AppCollectionsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/snippets/$id/edit': {
      id: '/_app/snippets/$id/edit'
      path: '/edit'
      fullPath: '/snippets/$id/edit'
      preLoaderRoute: typeof AppSnippetsIdEditRouteImport
      parentRoute: typeof AppSnippetsIdRoute
    }
  }
}

interface AppSnippetsIdRouteChildren {
  AppSnippetsIdEditRoute: typeof AppSnippetsIdEditRoute
}

const AppSnippetsIdRouteChildren: AppSnippetsIdRouteChildren = {
  AppSnippetsIdEditRoute: AppSnippetsIdEditRoute,
}

const AppSnippetsIdRouteWithChildren = AppSnippetsIdRoute._addFileChildren(
  AppSnippetsIdRouteChildren,
)

interface AppSnippetsRouteChildren {
  AppSnippetsIdRoute: typeof AppSnippetsIdRouteWithChildren
  AppSnippetsNewRoute: typeof AppSnippetsNewRoute
}

const AppSnippetsRouteChildren: AppSnippetsRouteChildren = {
  AppSnippetsIdRoute: AppSnippetsIdRouteWithChildren,
  AppSnippetsNewRoute: AppSnippetsNewRoute,
}

const AppSnippetsRouteWithChildren = AppSnippetsRoute._addFileChildren(
  AppSnippetsRouteChildren,
)

interface AppRouteRouteChildren {
  AppCollectionRoute: typeof AppCollectionRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppSnippetsRoute: typeof AppSnippetsRouteWithChildren
  AppCollectionsIdRoute: typeof AppCollectionsIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppCollectionRoute: AppCollectionRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppSnippetsRoute: AppSnippetsRouteWithChildren,
  AppCollectionsIdRoute: AppCollectionsIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
