apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/Meet-08/code_vault.git
    targetRevision: HEAD
    path: git-ops/charts/redis

  destination:
    server: https://kubernetes.default.svc
    namespace: code-vault

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
