apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd

spec:
  project: default

  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: postgresql
      targetRevision: 18

      helm:
        valueFiles:
          - $values/git-ops/charts/postgres/values.yaml

    - repoURL: https://github.com/Meet-08/code_vault.git
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: code-vault

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
